// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type Product struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Price float64 `json:"price"`
}

type ProductListInput struct {
	Name     *string  `json:"name"`
	MinPrice *float64 `json:"minPrice"`
	MaxPrice *float64 `json:"maxPrice"`
}
